### ISSUE TITLE
Please can you check this issue SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by newaeonweb** [yeoman/yeoman-test#12]
/home/ubuntu/generator-angm/node_modules/yeoman-test/node_modules/yeoman-generator/node_modules/read-chunk/index.js:2
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.

I have a generator-angm for AngularJS, but since yesterday Travis and Circle Ci give this error.

**Comment by SBoudrias** [comment]
Fixed with yeoman-generator 0.23.3
