### ISSUE TITLE
Warning for empty inputs

### ISSUE THREAD

**Issue by aeschli** [yeoman/yeoman-test#128]
There's now a message when an test input is not provided:
https://github.com/yeoman/yeoman-test/blob/373fbb6e385720a5cc39dd0466926a38c839e965/lib/adapter.js#L44

Unfortunately for us it's a false positive for cases where we allow empty inputs:
https://github.com/microsoft/vscode-generator-code/blob/07ae7522143dd5d32c8d6402eb6274cb8393765e/generators/app/generate-language.js#L66

In our test `this.question.type` is `input`, and `answer` is `""`

https://github.com/yeoman/yeoman-test/blob/373fbb6e385720a5cc39dd0466926a38c839e965/lib/adapter.js#L37
results in `isSet ===false`

**Comment by mshima** [comment]
I don't think this is a bug.

You should pass `{ tmLanguageURL: '' }` answer to yeoman-test in this case.
It should not print the warning due to https://github.com/yeoman/yeoman-test/blob/373fbb6e385720a5cc39dd0466926a38c839e965/lib/adapter.js#L43

As far as I remember `inquirer` never returns undefined if the prompt was shown.
So undefined is not a valid answer for that case.

**Comment by aeschli** [comment]
> You should pass { tmLanguageURL: '' } answer to yeoman-test in this case.

That's what I do. https://github.com/microsoft/vscode-generator-code/blob/07ae7522143dd5d32c8d6402eb6274cb8393765e/test/test.js#L444

`answer = this.question.default`

I probably should set the default to `` as well. But the message is misleading here as the answer was provided.

**Comment by mshima** [comment]
Ok. It’s a bug.

This assignment should be moved after the warning.
https://github.com/yeoman/yeoman-test/blob/373fbb6e385720a5cc39dd0466926a38c839e965/lib/adapter.js#L41

This condition should test if default is undefined too.
https://github.com/yeoman/yeoman-test/blob/373fbb6e385720a5cc39dd0466926a38c839e965/lib/adapter.js#L43

**Comment by mshima** [comment]
Fixed in https://github.com/yeoman/yeoman-test/commit/4f466bb06894c9bfcf8b86b7f8a88aaa774716c7
