### ISSUE TITLE
High vulnerability in yeoman-test

### ISSUE THREAD

**Issue by TCourtneyOwen** [yeoman/yeoman-test#134]
I am hitting the following vulnerabilities in yeoman-test v 4.0.0:

  High            Server-Side Request Forgery

  Package         axios

  Patched in      >=0.21.1

  Dependency of   yeoman-generator

  Path            yeoman-generator > yeoman-environment > npm-api >
                  paged-request > axios

  More info       https://npmjs.com/advisories/1594

  High            Server-Side Request Forgery

  Package         axios

  Patched in      >=0.21.1

  Dependency of   yeoman-test [dev]

  Path            yeoman-test > yeoman-environment > npm-api > paged-request >
                  axios

  More info       https://npmjs.com/advisories/1594

  High            Server-Side Request Forgery

  Package         axios

  Patched in      >=0.21.1

  Dependency of   yeoman-test [dev]

  Path            yeoman-test > yeoman-generator > yeoman-environment >
                  npm-api > paged-request > axios

  More info       https://npmjs.com/advisories/1594

**Comment by mshima** [comment]
Fixes at paged-request.
