### ISSUE TITLE
Error "Cannot find module 'mem-fs-editor'" when invoking the run-function

### ISSUE THREAD

**Issue by manuth** [yeoman/yeoman-test#138]
Since `mem-fs-editor` is not a dependency of `yeoman-test`, this piece of code causes an error sometimes:
https://github.com/yeoman/yeoman-test/blob/af0e8f1254167ea6c5682581df4fbe892ac6b05d/lib/run-result.js#L4

Me, in my case, I have `yeoman-test` installed (for testing) and `yeoman-environment` for injecting version `^3.0.0` into `yeoman-test` (as recommended in the [README](https://github.com/yeoman/yeoman-test#readme)).

For me, `mem-fs-editor` is being installed here: `node_modules/yeoman-environment/node_modules/mem-fs-editor`
`yeoman-test`, naturally, is being installed here: `node_modules/yeoman-test`.

When trying to run `yeoman-test` I get an error: `Cannot find module 'mem-fs-editor'`

`yeoman-test` assumes that `mem-fs-editor` is located directly in my `node_modules` folder, but that's not the case for me.
Personally I'd say the problem can be solved by adding `mem-fs-editor` to the `dependencies` of `yeoman-test`. I don't really want to fiddle around with my `package-lock.json` file

**Comment by mshima** [comment]
Fixed in 5.1.0
