### ISSUE TITLE
XO gives an error for new-cap on JSONFileContent

### ISSUE THREAD

**Issue by sondr3** [yeoman/yeoman-test#14]
I'm currently using XO together with Yeoman and it's test libraries, however XO trips up on one of the asserts used by `yeoman-test` called `JSONFileContent` due to the `new-cap` rule.

```sh

  test/gulp.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  test/uploading/aws.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  test/uploading/rsync.js:22:10
  ✖  22:10  A function with a name starting with an uppercase letter should only be used as a constructor.  new-cap

  3 errors
```

I'll refer to @sindresorhus comment [here](https://github.com/sindresorhus/xo/issues/119#issuecomment-222274035).

**Comment by SBoudrias** [comment]
We already renamed that function https://github.com/yeoman/yeoman-assert#assertjsonfilecontent

**Comment by sondr3** [comment]
Ah dang, that's what you get for reading the tests of other generators and not the documentation. Sorry.
