### ISSUE TITLE
Fix `yeoman-test` for NodeJS v16

### ISSUE THREAD

**Issue by manuth** [yeoman/yeoman-test#155]
`mem-fs-editor`s `delete`-function is not working with NodeJS 16 as noted here:
https://nodejs.org/api/fs.html#fs_fspromises_rmdir_path_options

This issue has been fixed with `mem-fs-editor@9.1.0`.

Please require `mem-fs-editor` > `9.1.0` for `yeoman-generator`.

**Comment by mshima** [comment]
Fixed in v6.3.0
