### ISSUE TITLE
RunContext#withGenerators() ignore composeWith with a local property

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman-test#16]
When using composition with a local path (`composeWith('gen:app', { local: 'local/path' })`), it ignores/bypass the generators mocks we setup on the RunContext with `#withGenerators()` as it requires/register the generator directly.

This should probably be fixed, I'm unsure about the correct solution ATM.

A potential solution I've come to think about is to mock the module require (with for example `proxyquire`).

(Moved from https://github.com/yeoman/generator/issues/704)

**Comment by addyosmani** [comment]
I think trying to leverage proxyquire for this use-case makes sense.

**Comment by groovytron** [comment]
I also have the same issue when I try to test my generator following [the documentation's testing example](https://yeoman.io/authoring/testing.html#test-helpers). I tried a few versions and I got it working by using `yeoman-test@1.9.0` so it looks like it's broken since `2.0.0`.

**Comment by groovytron** [comment]
I did not notice that my version of `yeoman-generator` was a long way behind so updating it to `yeoman-generator@4.5.0` fixed the issue.

**Comment by mshima** [comment]
I think this issue isn't applicable anymore.

Closing.
