### ISSUE TITLE
Pass namespace for helper.registerDependencies

### ISSUE THREAD

**Issue by lijunle** [yeoman/yeoman-test#17]
In [helper.registerDependencies](https://github.com/yeoman/yeoman-test/blob/master/lib/index.js#L185), there are two ways to register generator dependency.
1. Pass generator class. However, in this case, there is no way to specify the namespace.
2. Pass the generator path. However, the [`Environment.prototype.namespace`](https://github.com/yeoman/environment/blob/f2b0947b1d0c16ebf1207a438f8e990f5f5ef331/lib/environment.js#L400) is not smart enough to auto detect my namespace because I am writing generator in scope package. My main generator reports the composing generator is not found.

**Comment by SBoudrias** [comment]
FWIW If you're using `{local: path}` in your composeWith, registerDependencies is useless.

**Comment by lijunle** [comment]
I am not using `{local:path}`.

**Comment by SBoudrias** [comment]
@lijunle can you paste your code. It'll help when trying to figure out what is the issue/bug you're running into.

**Comment by addyosmani** [comment]
@lijunle It's been a while since the last ping on this issue. Should we assume you aren't able to share your code / close this or do you think you'll have a chance to get that together?

**Comment by lijunle** [comment]
Sorry, Currently, I am using such a hack to resolve it:

```js
helpers.registerDependencies = function (env, dependencies) {
  dependencies.forEach(function (dependency) {
    env.register.apply(env, dependency);
  });
};
```

**Comment by tonyhallett** [comment]
This is an issue.
[RunContext](https://github.com/yeoman/yeoman-test/blob/master/lib/run-context.js)
RunContext.prototype._run = function () {
...
helpers.registerDependencies(this.env, this.dependencies)
..
}
[helpers](https://github.com/yeoman/yeoman-test/blob/master/lib/index.js)
exports.registerDependencies = function (env, dependencies) {
  dependencies.forEach(function (dependency) {
    if (_.isArray(dependency)) {
      env.registerStub.apply(env, dependency);
...
}
[environment](https://github.com/yeoman/environment/blob/master/lib/environment.js)
Environment.prototype.registerStub = function registerStub(Generator, namespace) {
  if (!_.isFunction(Generator)) {
    return this.error(new Error('You must provide a stub function to register.'));
  }

  if (!_.isString(namespace)) {
    return this.error(new Error('You must provide a namespace to register.'));
  }

**Comment by guilhermevrs** [comment]
I was facing the exact same problem. Locally, yeoman-enviroment was working correctly and retrieving the correct namespace for the specific path.

But while running on jenkins for CI, the generator was not found.

What I did is to require the specific generator class and registered under the correct namespace
