### ISSUE TITLE
`yeoman-test` uses broken types

### ISSUE THREAD

**Issue by manuth** [yeoman/yeoman-test#178]
Hi Yeoman Team
The currently published version of `yeoman-test` uses a broken `@types`-package (one that prevents projects from building if they have the most recent `glob` version somewhere in the dependency tree).

Could you therefore please publish a patch release with its `@types/mem-fs-editor` set to `7.0.2` or newer?

Thank you so much for your effort!

**Comment by mshima** [comment]
Unfortunately it’s a npm design problem.
Updating mem-fs-editor types will not fix the problem.

**Comment by manuth** [comment]
`@types/mem-fs-editor` 7.0.2 and newer use `globby` instead of `glob` which therefore fixes the issue with the `glob` type collision.

I found a workaround that did the trick in my project. I deleted the `package-lock.json` file and did an `npm install` as this will automatically install the most recent `@types/mem-fs-editor`.

So this issue really isn't that urgent

**Comment by mshima** [comment]
`main` version already has updated packages.
But the problem may persist and is not fixable in our part.
Workarounds like this https://github.com/jhipster/generator-jhipster/blob/16f357c4b47add2340d1ab35cf256afacc27abe6/package.json#L85 could be used.

Closing.
