### ISSUE TITLE
end event not being called

### ISSUE THREAD

**Issue by jedireza** [yeoman/yeoman-test#18]
I'm upgrading from `yeoman-generator@0.22.x` to `yeoman-generator@0.24.x` and I'm unsure why my tests are timing out. Probably something obvious I'm overlooking. Any help is appreciated.

https://github.com/jedireza/generator-hapi-style/pull/30

**Comment by SBoudrias** [comment]
Are you using ˋthis.async` anywhere?

**Comment by jedireza** [comment]
In my generators, yes. Not in my test code though.

**Comment by jedireza** [comment]
😄 Ok got it. Thanks for the nudge. Turns out that callback support for `this.prompt(...)` was removed and it returns a promise now. I didn't expect that since on [yeoman.io/authoring/testing.html](http://yeoman.io/authoring/testing.html) there's a note:

> If you hate promises, you can use the `'ready'`, `'error'`, and `'end'` Events emitted

In any case, thanks again.
