### ISSUE TITLE
Alternatives for Deprecated Methods

### ISSUE THREAD

**Issue by manuth** [yeoman/yeoman-test#180]
According to the `tsdoc` comment, a wide variety of methods that I frequently used have been flagged as `@deprecated`:
  - both `cd` and `inDir` in `run-context.ts`
  - `mockPrompt` in `helpers.ts`

Has this been made on purpose?

If so:
What is the alternative to `mochPrompt`?
What is the alternative to `cd`/`inDir`?

**Comment by mshima** [comment]
Do you need `mockPrompt` in helpers?
Why not use in context?

**Comment by manuth** [comment]
Thank you so much for the recommendation.
I had a look at it.
Sadly, the context does not work for me. The `RunContext` will mock the prompts as soon as the environment is ready.
However, I register custom prompts in the constructor of the generator which therefore aren't getting mocked, so I need to call `mockPrompt` manually.

Is the generator construtor the wrong place to register custom prompts?

**Comment by manuth** [comment]
The prompts are mocked here:
https://github.com/yeoman/yeoman-test/blob/17ff3214dfece1f61711970ccb15e0a6bfe85494/src/run-context.ts#L368-L370

I register custom prompts in the generator's constructor:
https://codeberg.org/lordgizmo/TSProjectGenerator/src/commit/93b382928db91f8d7adfd6fff73517cc0d7c86ef/packages/generator-ts-project/src/Project/TSProjectGenerator.ts#L79-L80

However, `onEnvironment` is executed _before_ my generator's constructor. Thus, these prompts aren't getting mocked.

**Comment by mshima** [comment]
Ok, a custom prompt module.
Would be better to stub promptModule.register after
https://github.com/yeoman/yeoman-test/blob/17ff3214dfece1f61711970ccb15e0a6bfe85494/src/adapter.ts#L93
And register a dummy prompt instead of the actual prompt.

**Comment by manuth** [comment]
> Ok, a custom prompt module.
> Would be better to stub promptModule.register after
> https://github.com/yeoman/yeoman-test/blob/17ff3214dfece1f61711970ccb15e0a6bfe85494/src/adapter.ts#L93
> And register a dummy prompt instead of the actual prompt.

Awesome!
Thank you so much for the advice

**Comment by mshima** [comment]
> Ok, a custom prompt module. Would be better to stub promptModule.register after
> 
> https://github.com/yeoman/yeoman-test/blob/17ff3214dfece1f61711970ccb15e0a6bfe85494/src/adapter.ts#L93
> 
> 
> And register a dummy prompt instead of the actual prompt.

Implemented in https://github.com/yeoman/yeoman-test/commit/623019a62689bcbf2630e6e298d9f03b5c21a6a8.
