### ISSUE TITLE
getSnapshot with filter also adds .ejs files in the snap file

### ISSUE THREAD

**Issue by sam0410** [yeoman/yeoman-test#183]
I did :

```
result.getSnapshot(file => {
          return !(file.path.endsWith('TestData.java'))
```
This added .ejs file in the `generator.spec.mjs.snap` file. 

Although it got fixed by 
```
result.getSnapshot(file => {
          return !(file.path.endsWith('TestData.java') || file.path.endsWith('.ejs'))
```

I don't think `.ejs` files or infact no template files should be included in the first place.

**Comment by sam0410** [comment]
The culprit is in this line : https://github.com/mshima/mem-fs-editor/blob/master/src/actions/dump.ts#L24 

When we pass a non-null non-string filter, it does not use the `defaultDumpFilter`

Will make the change.

**Comment by mshima** [comment]
Providing a function filter will override default filter that [removes untouched](https://github.com/SBoudrias/mem-fs-editor/blob/59d2bc9bc0bda3012bf0ec0b99b068553f192da4/src/actions/dump.ts#L24) files. You can:
- filter by yourself.
- use pattern like `result.getSnapshot('**/*.java');`

**Comment by sam0410** [comment]
Shouldn't the line that you mentioned (i.e., line 24) entail `filter ? (filter && defaultDumpFilter) : defaultDumpFilter`. 

No filter should contain non template files.

**Comment by mshima** [comment]
I would say that the most important filter is to filter by the test result's cwd.
EJS files will probably outside the result cwd.
Dumping all files may be interesting for files written outside apis.
But converting the filter parameter to an object and adding flags should be ok.
