### ISSUE TITLE
generator.run() should not fail silently if there is a problem with running generator

### ISSUE THREAD

**Issue by xelibrion** [yeoman/yeoman-test#2]
Hey guys,

I've recently started writing my own generator and one of the problems I've encountered is behaviour of RunContext when running generator fails for some reason. In my case there was one of the parameters missing in the template and it took quite some time to figure out why `this.fs.copyTpl(...)` was preventing generator in my tests from receiving `end` event.

Would be great to make test helpers more developer-friendly - not sure if it would require changes in the core library.

**Comment by SBoudrias** [comment]
PR welcomed.

**Comment by SBoudrias** [comment]
I added a new method today called `toPromise()`. This should ease the handling of errors in test as you can now just return the promise inside the `beforeEach()` setup phase and it'll fail the test if the promise is rejected.

That mean you don't have to manually handle errors.

I'll make a new release soon.
