### ISSUE TITLE
Where did  `generator.destinationRoot` move to?

### ISSUE THREAD

**Issue by emilkrebs** [yeoman/yeoman-test#212]
I used  `generator.destinationRoot(targetRoot, false);` before to change the destination directory of the generator. However, in the latest release the arguments were removed. 

Example:
```ts
...
context.targetDirectory = path.join(__dirname, '../../../examples/hello-world');
context.onGenerator(async (generator) => {
                // will generate into examples/hello-world instead of examples/hello-world/hello-world
                generator.destinationRoot(targetRoot, false);
            })
...
```

What should I use instead?

**Comment by mshima** [comment]
The api is in the generator:

**Comment by emilkrebs** [comment]
Thanks! Do you know how I can get the types?
