### ISSUE TITLE
Object is misspelled in one of the @param docs

### ISSUE THREAD

**Issue by tkreis** [yeoman/yeoman-test#22]
it says:   `{Ojbect} ` instead of `{Object}`
https://github.com/yeoman/yeoman-test/blob/master/lib/index.js#L129

**Comment by mischah** [comment]
Ha, good catch 👌 
Like to create a pull request? You have been almost there 😏

Just head back to https://github.com/yeoman/yeoman-test/blob/master/lib/index.js and hit the pencil icon 😘 

![image](https://cloud.githubusercontent.com/assets/441011/20631415/96c89df4-b336-11e6-8200-0e2a1eebfab3.png)

**Comment by mischah** [comment]
Fixed with a53bb9c38b8b40fcba5e80c41ed976aa7588767a
