### ISSUE TITLE
How change current working dir for new runcontext using  helper.run()...result.create().run() ?? 

### ISSUE THREAD

**Issue by ztaf** [yeoman/yeoman-test#244]
Hi!

Thanks for an aweome test library for Yeoman!

I use a number of generators for "initial-creation" and "updating" a repo structure for a coding project.

When running a combined test for "inital-creation" and then "updating", I need to cd into a subfolder, so logically it is what I would like to happen:

1) Run generator an create initial structure (will create a repo under folder "myapp_name")
2) cd into folder "myapp_name"
3) Run generattor for updating structure

Now how can I perform this cd step using/constructing my test li7ke so:

helper.run()...result.create().run() ??

Thanks in advance for guidance!

**Comment by mshima** [comment]
Maybe:
```
await helper.run(...);
process.chdir(...);
await result.create(...);
```

**Comment by ztaf** [comment]
Great! Thanks!
