### ISSUE TITLE
`filter` function is not executed by test

### ISSUE THREAD

**Issue by SamVerschueren** [yeoman/yeoman-test#29]
I noticed that the filter is not being executed by the tester. I changed [this](https://github.com/yeoman/yeoman-test/blob/master/lib/adapter.js#L39) line to

```js
return Promise.resolve(this.question.filter ? this.question.filter(answer) : answer);
```

And now everything seems to be working as expected. Not sure if it's that easy to fix though.

**Comment by SBoudrias** [comment]
This wouldn't support async filters and it doesn't pass the proper arguments. Given we're mocking inquirer, not running any settings function made sense for us.

**Comment by SamVerschueren** [comment]
The `default` property is taken into account currently though.

The thing is that I was refactoring a filter function and wanted to test if it worked correctly. For instance, `Array.prototype.includes` only works on Node.js 6 if I'm not mistaken. So if I would test my generator on Node 4 and 6 (LTS), my tests will pass. But if someone installs the generator and runs it, it will crash and 🔥.

In my `generator-alfred` workflow, I prepend the workflow name with `alfred-` if it's not already present, I add it in the [filter function](https://github.com/SamVerschueren/generator-alfred/blob/master/app/index.js#L16-L24). So currently, I'm not able to entirely test my workflow.

I just wanted to make sure if this was on purpose or not. I can always take a look to do a PR. But it's your call to make off course :).

**Comment by marcofugaro** [comment]
Yeah it was weird when I found this issue, I can't replicate fully the generator behavior in a testing environment

**Comment by dankreft** [comment]
Any chance of getting this fixed? I was surprised and disappointed to see that the filter is completely ignored.

**Comment by marcofugaro** [comment]
Only 15 days?? 🤣🤣🤣

**Comment by mshima** [comment]
@marcofugaro you just found a bug, please report at https://github.com/yeoman/yeoman-test/issues/new

The relevant part is:
https://github.com/yeoman/yeoman-test/blob/46c518380d8e82b1df3209757ed13cb3f5f83d4c/.github/workflows/stale.yml#L13-L15

Just kidding, I am cleaning up irrelevant old issues.

About this issue, I don't now much about inquirer:
> This wouldn't support async filters and it doesn't pass the proper arguments. Given we're mocking inquirer, not running any settings function made sense for us.

But added a way to workaround it at https://github.com/yeoman/yeoman-test/pull/73

**Comment by mshima** [comment]
Test cases are controlled environment.
In order to test filters, you should use: 
`withPrompts({ yeoman: 'no please' }, answer => this.question.filter(answer))`

**Comment by niksy** [comment]
What is the proper way of testing `filter` function? @mshima’s recommendation in last comment doesn’t actually work since it uses arrow function, and converting it to classic function produces another type of error.
