### ISSUE TITLE
It should remove tmp folder after the tests

### ISSUE THREAD

**Issue by TheSavior** [yeoman/yeoman-test#3]
yeoman-test creates a tmp folder to execute in. This tmp folder is not cleaned up after runs and causes our build machines to run out of disk space very quickly. 

It would be great if there was a yeoman-test function that could be called to clean up (rimraf the folder it used) in an afterEach block.

**Comment by SBoudrias** [comment]
@TheSavior usually OS automatically clean up temporary folders when they're getting too big. Your CI should probably add a step to clean the tmp folder after each suite runs if you have an issue.

I'm not sure that's something we should take care of inside of `yeoman-test`.

**Comment by TheSavior** [comment]
That is not standard behavior at least on CentOS. I believe the default behavior is for the tmp directory to be cleaned as part of a daily cron. We are just adding the afterEach hook in our project and writing it ourselves. I imagine other people may hit this, so if nothing else, hopefully this ticket can help people in the future.

**Comment by SBoudrias** [comment]
@TheSavior Can't you just add a step to your build scripts to `rm -rf $TMPDIR/**` after each runs? In jenkins or whatever CI you're using.

**Comment by TheSavior** [comment]
Kinda sorta. Depends if anything else is running on the box that has open files in tmp. We have a solution, but it's something to keep in mind.

**Comment by eddiemonge** [comment]
While I agree that this sounds more like a user problem (CI system) there is a way to do it but might need an additional thing added. helpers.createTestDirectory currently empties the test folder but only if you pass it a directory. It doesn't look like the current tmp directory is saved anywhere where it could be passed to that method
