### ISSUE TITLE
inDir & cd create files in the project root path

### ISSUE THREAD

**Issue by unbug** [yeoman/yeoman-test#30]
In my case I want to share the RunContext tmp dir in two generator by set it in the inDir or cd pipeline, it does work,  but instead generate files in the tmp dir it create them in my project root dir. What I did wrong?
```
  beforeAll(() => {
    return helpers.run(path.join(__dirname, '../generators/app'))
      .inDir(path.join(__dirname, './tmp'))
      .withOptions({'skip-install': true})
      .withPrompts({name: projectName});
  });

  beforeAll(() => {
    return helpers.run(path.join(__dirname, '../generators/module'))
      .inDir(path.join(__dirname, './tmp'))
      .withArguments([moduleName]);
  });
```

**Comment by SBoudrias** [comment]
There's probably a `.yo-rc.json` files at the root of your project. You should setup `inDir` in your computer temporary file folder.

**Comment by unbug** [comment]
@SBoudrias is it a good idea to setup `.inDir('./tmp')` ? then I have to clean the tmp dir for that, can we add setting in `.yo-rc` to avoid this?

**Comment by SBoudrias** [comment]
`.inDir(path.join(require('os').tmpdir(), 'my-test-folder/'))` is simpler and won't require any change.

**Comment by unbug** [comment]
Just test it, the sub-generator won't create files in the os tmp dir, not sure why. I have ho delete `.yo-rc.json`. Now below work for me.
```
  beforeAll(() => {
    return helpers.run(path.join(__dirname, '../generators/app'))
      .inDir(path.join(__dirname, '../tmp'))
      .withOptions({'skip-install': true})
      .withPrompts({name: projectName});
  });

  beforeAll(() => {
    return helpers.run(path.join(__dirname, '../generators/module'))
      .cd(path.join(__dirname, '../tmp'))
      .withArguments([moduleName]);
  });
```
