### ISSUE TITLE
How to test the 'yosay' calls?

### ISSUE THREAD

**Issue by lenin-anzen** [yeoman/yeoman-test#33]
I am trying to test the **yosay** calls to confirm that they are correctly executed.

I am using the default Jest test.

**\__tests\__/app.js**
```js
const path = require('path');
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');

describe('generator-myown-generator:app', () => {
    beforeAll(() => {
      return helpers.run(path.join(__dirname, '../generators/app'))
        .withPrompts(prompts)
        .withArguments(['noinstall'])
        // Construct a test scenario
        .inTmpDir(dir => {
          console.log('App: Files saved on temporal directory:', dir);
        });
    });
    it('Calls the yosay', () => {
        console.log = jest.fn();
        expect(console.log).toBeCalled();
    });
});
```
**generators/app/index.js**

```js
class AppClass extends Generator {
  prompting() {
    this.log(yosay(
      'Welcome to the awesome ' + chalk.red('myown-generator') + ' generator!'
    ));
  }
}
```

But it did not work. I am trying also with the **--verbose** argument. And the yosay calls are never showed up.

**Comment by SBoudrias** [comment]
Tests run with a TestAdapter that swallow writes to the console: https://github.com/yeoman/yeoman-test/blob/master/lib/adapter.js

Also, in your test, you're mocking `console.log` after it'd actually be use.

You can use the `on('ready')` hook to mocks function on your generator instance.
