### ISSUE TITLE
Util inherits is discouraged by Node

### ISSUE THREAD

**Issue by mike3run** [yeoman/yeoman-test#35]
https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor

In
https://github.com/yeoman/yeoman-test/blob/master/lib/run-context.js#L46

Class Extension is the more favoured thing

![screen shot 2017-07-18 at 9 27 41 pm](https://user-images.githubusercontent.com/7088511/28347976-f6ff076c-6bff-11e7-9b7f-4fb0c4f63c4a.png)

May be related to this message about EventEmitters limit reached 😢

**Comment by SBoudrias** [comment]
Yeah, this code was authored before JS classes were a thing.

PR is welcomed

**Comment by mike3run** [comment]
🤷‍♂️
