### ISSUE TITLE
Allow for step between tmpdir created and generator run

### ISSUE THREAD

**Issue by mlucool** [yeoman/yeoman-test#37]
Allowing for a step between the tmpdir and generator run allows for testing of situations when there are files already in a directory and how the script reacts to them. Can this please be added or documented if this is already possible?

Thanks!

**Comment by SBoudrias** [comment]
I think there's a lot of example in our documentation covering this case http://yeoman.io/authoring/testing.html

Either use the callback from the `inTmpDir()` function or catch the `ready` event.

I'll close this issue as it seemed to be supported, but let me know if I didn't understood your issue properly.

**Comment by mlucool** [comment]
Ah I was wrong on the reason for my issue. I made a poor assumption here I'll open up a new one that is more accurate
