### ISSUE TITLE
While testing, how to pass prompt values for dependency generator called using composeWith.

### ISSUE THREAD

**Issue by CarreraPHP** [yeoman/yeoman-test#39]
# how to pass prompt values for dependency generator called using composeWith.

I am in the process of create a mysql based generators & its sub-generators, The way the generators works is as below.

When the app generator is run, its prompts questions to collect values like "host", "username" & "password" with these answers the generator initial a connect to the mysql server and awaits for the response. When the response is received, the user should be prompted to choose the schema he wants to work with. To achieve this, i am having another sub generator which will gets the connections details using ```composeWith``` options parameter and make mysql connection and will show the list of Schema available from the mysql server as a list prompt. The same process is repeated for table and columns and relationships as well.

I am able to write test case and it is working based on the default values provided to the sub generator's prompts. but i am not able to different value to the sub generators as part of assertions. I went through the source of yeoman-test and yeoman-assert but i am not able to find any method through which i can achieve this.

## **Example Code**

**app/index.js generator**
```javascript
  get install() {
    return {
      callSubgenerator() {
        this.composeWith(require.resolve('../entitycolumn/index.js'));
      },
      doInstallDependencies() {
        this.installDependencies();
      }
    };
  }
```

**entitycolumn/index.js generator**
```javascript
  prompting() {
    console.log('running sub generator');

    // Have Yeoman greet the user.
    this.log(
      yosay('Welcome to the priceless ' + chalk.red('generator-jdl') + ' generator!')
    );

    //prompt for schema list should come here...
    const prompts = [
      {
        type: 'input',
        name: 'host',
        message: 'Provide the Hostname for the Mysql Server',
        default: 'localhost'
      },
      {
        type: 'input',
        name: 'username',
        message: 'Provide the Username for the Mysql Server',
        default: 'root'
      },
      {
        type: 'password',
        name: 'password',
        message: 'Provide the Password for the Mysql Server',
        default: 'root'
      }
    ];

    return this.prompt(prompts).then(props => {
      // To access props later use this.props.someAnswer;
      this.props = props;
    });
  }
```

**__tests__/app.js  jest test suite file**
```javascript
'use strict';
const path = require('path');
// Const fs = require('fs');
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');

describe('generator-jdl:app', () => {
  beforeAll(() => {
    /* GLOBAL */
    jest.setTimeout(100000);
    console.log('for cred prompt', {
      host: '127.0.0.1',
      username: 'root',
      password: 'root'
    });

    var deps = [[helpers.createDummyGenerator(), '../entitycolumn/index.js']];
    // Var otherDeps = [
    //   [
    //     helpers.createGenerator(
    //       require.resolve('../generators/entitycolumn/index.js'),
    //       null,
    //       [],
    //       null
    //     ),
    //     '../entitycolumn/index.js'
    //   ]
    // ];
	
	// I need some mechanism like below to send the answers for prompts like 
	// 'withPrompts' method at line 39 in generator called with composeWith.
	// Below is not working.
    helpers.mockPrompt(deps[0][0], {});

    return (
      helpers
        .run(path.join(__dirname, '../generators/app'))
        .withGenerators(deps)
        .withArguments(['l27.0.0.1', 'root', 'root'])
        .withPrompts({ schema: 'DBSCHEMA' })
        .inTmpDir(dir => {
          // `dir` is the path to the new temporary directory
          console.log(
            `${dir}/DBSCHEMA.jh \n=-=-=-=-=-=-=-=-=-=-=-=-=-=-= \n${path.join(
              __dirname,
              `dummyfile.jh`
            )}`
          );
        })
    );
  });

  it('creates files', () => {
    assert.file(['DBSCHEMA.jh']);    
  });
});
```
Hope, I have exemplified my need through the above sample code.

Regards,
Yogesh Surendran

**Comment by CarreraPHP** [comment]
@SBoudrias, any suggestions/help on this?

**Comment by SBoudrias** [comment]
I believe `withPrompts` is applied to all generators run (the main one and the composed ones).

Please, do not duplicate your question on all repos. Once is enough.

**Comment by CarreraPHP** [comment]
@SBoudrias ,the ```withPrompts``` works as you implied with one limitation, the prompts name should be unique across all the sub-generator.  This is something ppl should remember, is it possible to add one line about it [yeoman testing url](http://yeoman.io/authoring/testing.html)

**Comment by SBoudrias** [comment]
@CarreraPHP care to send a PR to clarify the documentation on this point?
