### ISSUE TITLE
Local config interferes with tests

### ISSUE THREAD

**Issue by coaxial** [yeoman/yeoman-test#45]
If I am developing a generator and `npm link` it so I can run it locally, the stored config will interfere with the unit tests.

The prompts that have `store: true` will also use their stored values when running the tests in jest. Even passing `.withLocalConfig({})` doesn't seem to alleviate the issue: the stored config is used.

Even selecting "Clear local config" in `yo` doesn't help. 

It seems like some kind of caching issue that I can't find the root cause of. Any ideas?

**Comment by SBoudrias** [comment]
Yes `store: true` use a global config - not the local one.

We could add a mockGlobalConfig; in the same way local config mock works. Would you mind to send a PR?

**Comment by coaxial** [comment]
Sure, I'll see what I can do.

**Comment by mshima** [comment]
Fix is split into 3 parts:
Generator: https://github.com/yeoman/generator/pull/1161 release
Environment: https://github.com/yeoman/environment/pull/155 release
Test: in progress.

**Comment by Xesenix** [comment]
I am not sure if those changes didn't break testing. When you provide answers `withPrompts` they do not fill configuration available via `this.config.getAll()`.

For example, I have generator that uses something like this:
```
const { promptValues: { somePrompt, }, } = this.config.getAll();
```
when I try to add prompt anwser in test via:
```
beforeAll(() => {
  return helpers
    .run(path.join(__dirname, '../generators/app'))
    .withPrompts({ somePrompt: 'zxc' })
});
```
I will get:
```
TypeError: Cannot destructure property `somePrompt` of 'undefined' or 'null'.
```
Which looks like the mocking mechanism for prompts is not fully simulating true behaviour of generato when running from CLI which provides this value without issues.

**Comment by mshima** [comment]
> Which looks like the mocking mechanism for prompts is not fully simulating true behaviour of generato when running from CLI which provides this value without issues.

Hello @Xesenix promptValues is not supposed to be used that way. Actually is an internal cached prompt value and I think it shouldn’t be used at all. It can cause unexpected side effects.
It’s related to skipCache configuration:
 https://github.com/yeoman/yeoman-test/blob/422d26ca54d6136678aa009e0d251392f9e9df0b/lib/run-context.js#L61

withPrompts method doesn’t fill those values, it creates a custom inquirer instance with built in answers.

**Comment by Xesenix** [comment]
I was looking for a way to split generators into smaller feature generators but also keep some global configuration that can be used to modify templates. Like I have generator that asks if user wants to use react and if he does some other generator uses template variation basing on what user has chosen.  But to achieve that I need to get answers from sub-generator prompts and only way I see that can be done is to use this `const { promptValues: { somePrompt, }, } = this.config.getAll();`

For example like here 
_(WIP: still trying to figure out what I can and cannot do)_
https://github.com/Xesenix/generator-xes-bdf/blob/master/generators/add-app/index.js#L81
this generator uses sub generators to get some additional configuration. I guess the issues you mention are like overriding prompt values when they are called multiple times that I solved by addig some restrictions to prompts via `deps` option. 

So I guess what you are meaning by:

> Actually is an internal cached prompt value and I think it shouldn’t be used at all. It can cause unexpected side effects.

there just doesn't exist legit way to communicate configuration from sub generators to parent generator. And only proper way to do that would be request multiple times the same information from user or implement own prompting system?

Also, this place sound like bad place to discouse that do you have some place for discusing features or design decisions?

**Comment by mshima** [comment]
> I was looking for a way to split generators into smaller feature generators but also keep some global configuration that can be used to modify templates. Like I have generator that asks if user wants to use react and if he does some other generator uses template variation basing on what user has chosen. But to achieve that I need to get answers from sub-generator prompts and only way I see that can be done is to use this `const { promptValues: { somePrompt, }, } = this.config.getAll();`
> 
> For example like here
> _(WIP: still trying to figure out what I can and cannot do)_
> https://github.com/Xesenix/generator-xes-bdf/blob/master/generators/add-app/index.js#L81
> this generator uses sub generators to get some additional configuration. I guess the issues you mention are like overriding prompt values when they are called multiple times that I solved by addig some restrictions to prompts via `deps` option.
> 
> So I guess what you are meaning by:
> 
> > Actually is an internal cached prompt value and I think it shouldn’t be used at all. It can cause unexpected side effects.
> 
> there just doesn't exist legit way to communicate configuration from sub generators to parent generator. And only proper way to do that would be request multiple times the same information from user or implement own prompting system?
> 
> Also, this place sound like bad place to discouse that do you have some place for discusing features or design decisions?

This should be moved to yeoman/generator.
There are some alternatives:
- Use this.options.sharedData (yeoman-environment@2.8.0)
- Use this.composeWith(subGen, {}, true), the true will make composeWith return the subGen instead itself. Do whatever you want with if. (yeoman-generator@4.6.0)
- this.config.set('foo', value) on any generator. Will be immediately available on any other generator with this.config.get('foo'). Only with same namespace (package).

**Comment by mshima** [comment]
@Xesenix I just saw your implementation and looks like you just need to do on one gen:
`this.config.set(await this.prompt()):`

On the other gen is just `this.config.getAll();`
