### ISSUE TITLE
1.9.0 fails our tests

### ISSUE THREAD

**Issue by ChrisBAshton** [yeoman/yeoman-test#48]
Jenkins build failing today with the following error:

```
/app/packages/generator-vj/node_modules/yeoman-test/lib/run-context.js:121
  this.generator.run().catch(err => this.emit('error', err));
                            ^

TypeError: this.generator.run(...).catch is not a function
    at RunContext._run (/app/packages/generator-vj/node_modules/yeoman-test/lib/run-context.js:121:29)
    at RunContext.<anonymous> (/app/packages/generator-vj/node_modules/yeoman-test/lib/run-context.js:59:10)
    at /app/packages/generator-vj/node_modules/lodash/lodash.js:5138:35
    at /app/packages/generator-vj/node_modules/yeoman-test/lib/index.js:93:5
    at next (/app/packages/generator-vj/node_modules/rimraf/rimraf.js:75:7)
    at CB (/app/packages/generator-vj/node_modules/rimraf/rimraf.js:111:9)
    at /app/packages/generator-vj/node_modules/rimraf/rimraf.js:137:14
    at FSReqWrap.oncomplete (fs.js:152:21)
```

We've fixed by locking our version down to `~1.8.0`.

**Comment by SBoudrias** [comment]
Hey @ChrisBAshton sorry for the trouble. Could you help me dig into this one as to why it started to fail?

Are you using an old version of `yeoman-generator`?

**Comment by adamgruber** [comment]
When `yeoman-generator` v3 was released, it updated the `generator.run()` method to return a promise. [This `yeoman-test` commit](https://github.com/yeoman/yeoman-test/commit/06f2d6da248f92cdcaf875f1d8739a4c85fc253a) adds a `catch()` to the `generator.run()` call which will fail if you do not have `yeoman-generator` > 3.

Looks like `1.9.0` should have been `2.0.0` as this was a breaking change. Updating `yeoman-generator` should fix this issue but if you can't do that, pinning to `1.8.0` is the other option.

**Comment by SBoudrias** [comment]
Republished 1.9.0 as 2.0.0 and reverted to latest version working with yeoman-generator 2.0 as 1.9.1

Hope this will help those of you unable to upgrade to latest yeoman-generator right now.
