### ISSUE TITLE
inTmpDir could try to remove an existing directory

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-test#5]
Extremely rare chance but inTmpDir could try to remove an existing folder in the tmp directory. This line doesn't do a check to see if it exists before removing it https://github.com/yeoman/yeoman-test/blob/v1.1.0/lib/run-context.js#L139

**Comment by SBoudrias** [comment]
I think this is a correct behavior given it's a temporary directory. There's no guarantee data should stay in there.

Did you run into issues caused by this behavior?

**Comment by eddiemonge** [comment]
I don't think I did. I think its just an edge case I saw when looking at the code
