### ISSUE TITLE
New release on NPM for v2?

### ISSUE THREAD

**Issue by hassankhan** [yeoman/yeoman-test#54]
Hi there,

It seems there's a commit for v2, but no corresponding release on NPM. Could this be rectified please? 😄

**Comment by SBoudrias** [comment]
Version 2 is released, but we release a fix for the v1 branch in between which is why it shows as the latest on npm.

See: https://www.npmjs.com/package/yeoman-test

**Comment by SBoudrias** [comment]
I've updated the `latest` tag to 2.0 so it shows properly on npm.
