### ISSUE TITLE
depInstall save doesn't work in tests

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-test#6]
Since npm/bower do the saving themselves, the tests don't reflect this.

**Comment by SBoudrias** [comment]
`skipInstall` is setup by default, could that be your issue?

**Comment by eddiemonge** [comment]
Probably. That is odd though since running the generators normally don't have that by default so the tests are not entirely accurate. I wonder if there is a way to mock that out somehow? It'll probably be pretty ugly though

**Comment by SBoudrias** [comment]
Just use `withOptions({'skip-install': false})`

**Comment by eddiemonge** [comment]
Thats what I mean. I want fast tests, but with the save. I guess thats more of an integration test though and assuming npm/bower works might be the only way
