### ISSUE TITLE
Test scaffolding out in alternative to the os temp folder

### ISSUE THREAD

**Issue by danpetitt** [yeoman/yeoman-test#61]
I am having problems running the tests in our CI environment because the OS tmp folder is locked down; so after reading around I discovered the `helper.inDir` method.

However, setting the parameter to a custom folder which I can then exclude from distribution doesnt do anything ... the tmp folder which the tests create, now sits in the main project folder and not the os.tmp folder, however, but its not what i was expecting

Any idea what I am doing wrong here?

```
const tempFolderPath = `${path.join(__dirname, '../test_tmp/')}/${uuidv4()}/`;

helpers
    .run(path.join(__dirname, '../generators/app'))
    .inDir(tempFolderPath)
    .withOptions({ skipInstall: true })
    .withPrompts(defaultAnswers)
    .on('end', done);
```

I have also tried creating the temp folder myself and then `cd` ing into it, but again it just creates the test generator structure in the project folder.
```
const tempFolderPath = `${path.join(__dirname, '../test_tmp/')}/${uuidv4()}/`;

helpers
    .run(path.join(__dirname, '../generators/app'))
    .inDir(tempFolderPath)
    .withOptions({ skipInstall: true })
    .withPrompts(defaultAnswers)
    .cd(tempFolderPath)
    .on('end', done);
```

Apologies in advance if this isnt a bug, and just my usage.

**Comment by SBoudrias** [comment]
Any chance the place the project is generate changes because there's a `.yo-rc.json` file in a parent folder?

**Comment by danpetitt** [comment]
I do have a file in project folder but it is currently empty; should I remove it?

**Comment by danpetitt** [comment]
Removing the rc file worked; cool thanks @SBoudrias
