### ISSUE TITLE
Inconsistent links to API documentation

### ISSUE THREAD

**Issue by mdotasia** [yeoman/yeoman-test#7]
When I click the documentation link in the README I end up on this page: http://yeoman.io/authoring/testing.html

There are 2 API links on this page:
- Section **Others** links to http://yeoman.io/generator/module-test_helpers.html
- The Full API link in menu on right links to http://yeoman.io/generator/ which does not include the test API

**Comment by SBoudrias** [comment]
We don't maintain an API documentation for the test module anymore. I've removed the link from our documentation.

You're free to dig in the code for some legacy methods, but I wouldn't suggest using them over what is covered on our testing documentation page.

If you feel anything is missing, please let us know or send a PR to fill in the blanks. Help is always warmly welcomed.
