### ISSUE TITLE
Enable gh pages for yeoman test

### ISSUE THREAD

**Issue by mshima** [yeoman/yeoman-test#74]
Jsdoc has been publisher to gh-pages branch.
It should be enabled on the project settings.

**Comment by SBoudrias** [comment]
Hey @mshima this should work, I'm not sure why it 404.

Any chance there's no index file or the format is invalid for gh-pages?

<img width="759" alt="Screen Shot 2020-02-17 at 12 04 49 AM" src="https://user-images.githubusercontent.com/923865/74608114-59bfdd80-5119-11ea-88bc-335d2fbe755e.png">

**Comment by mshima** [comment]
It's working now.
Thanks @SBoudrias
