### ISSUE TITLE
Test running commands in test directory

### ISSUE THREAD

**Issue by robkinyon** [yeoman/yeoman-test#8]
I'm writing a generator which provides certain commands as part of its creation. For example, `npm run test` or `grunt test` or whatever. I'd like to be able to verify that they will run properly in my generator's test suite. A naive attempt didn't work:

```
var exec = require('child_process').exec;
[snip]
    it("provides 'npm run test'", function (done) {
        exec('npm run test', function (err, stdout, stderr) {
          if (err) {
            assert.ok(false, stderr);
          }
          else {
            assert(true, stdout);
          }
          done();
        }
      }
    });
```

I get the following in `err` and nothing in `stdout` or `stderr`:
```
{ [Error: Command failed: /bin/sh -c npm run test
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c npm run test' }
```
It's not clear what my next step would be.

**Comment by SBoudrias** [comment]
Did you try [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). Also make sure you're spawning the command in the right directory.

This is all Node.js API. Yeoman doesn't change or handle these functions for you.

**Comment by robkinyon** [comment]
`exec()` is a wrapper around `spawn()`, so, yes, I did try `spawn`. I also tried `spawn` directly with identical results (which is good, if you think about it).

I also confirmed I was in the right directory by doing an `ls -la` and confirming that I have the files I expected to have. I was also able to `cat package.json` and see what I expected from my template.

Is there a reason you can think of why standard Bash commands would work, but `npm` would not?

**Comment by SBoudrias** [comment]
You did `exec('ls -la')` and that gave you the expected output?

Any chance npm is not on the path of the user running the exec command?
