### ISSUE TITLE
`inDir` deletes contents of directory before generation

### ISSUE THREAD

**Issue by scalvert** [yeoman/yeoman-test#86]
Currently, the `inDir` method will delete the contents of the specified directory prior to the generator running.

https://github.com/yeoman/yeoman-test/blob/master/lib/index.js#L86

Can we add a flag to skip this defaulting to preserving the current behavior for backwards compatibility?

```
deleteDirContents = true
```

I assume we'd thread this through to https://github.com/yeoman/yeoman-test/blob/master/lib/index.js#L75

**Comment by mshima** [comment]
> Can we add a flag to skip this defaulting to preserving the current behavior for backwards compatibility?

Which version didn’t deleted?
I think `cd` is what you are looking for.

**Comment by scalvert** [comment]
Sorry, my description wasn't good. I don't want it to delete the contents. I'm using `fixturify-project` to scaffold out a specific project structure, which I want to then run the generator against. So, I want to skip deleting directory contents. Probably `skipCleanup` is a better param name.

**Comment by mshima** [comment]
Actually I understood.
But I don’t think is a regression.
You should use `cd` method instead.
https://yeoman.github.io/yeoman-test/RunContext.html#cd

**Comment by mshima** [comment]
The feature request is already implemented.

**Comment by scalvert** [comment]
Ugg you're right. I swear I tried this first. Let me try again!
